### ISSUE TITLE
코드 레이아웃 변경 제안

### ISSUE THREAD

**Issue by yeonduing** [Nexters/Fancy-Mouse-iOS#4]
@lsh424 승환님 많은 레퍼런스를 읽고 팀 스타일 가이드 작성해주셔서 감사합니다🙇‍♀️
양이 많아 오랜 시간이 걸리셨을 텐데 이렇게 잘 정리해주셔서 감동이에요👍🤭
[팀 Swift Style Guide](https://github.com/Nexters/Fancy-Mouse-iOS/wiki/%ED%8C%80-Swift-Style-Guide#%EC%BD%94%EB%93%9C-%EB%A0%88%EC%9D%B4%EC%95%84%EC%9B%83)

작성해주신 코드 레이아웃에서 수정 제안드리고자 하는 부분이 있어 이슈 남깁니다🙇‍♀️

<img width="910" alt="스크린샷 2022-01-26 오후 9 51 20" src="https://user-images.githubusercontent.com/60538517/151166149-bc2a5f31-7924-4664-ad84-ee6302538a7d.png">

이라고 해주셨는데 [google.github.io/swift/](https://google.github.io/swift/)를 참조하여

<img width="778" alt="스크린샷 2022-01-26 오후 9 49 20" src="https://user-images.githubusercontent.com/60538517/151166436-a09881ec-2470-4aeb-bec4-c08d17f21342.png">

<img width="758" alt="스크린샷 2022-01-26 오후 9 55 15" src="https://user-images.githubusercontent.com/60538517/151166601-16782c9b-0e44-4987-b9a5-ab41a5cd1702.png">

클로저의 경우 Void를 넣지만 펑션의 경우 생략하는 것을 제안 드립니다.

**Comment by lsh424** [comment]
네 좋아요! Style Guide는 제가 수정해놓겠습니다. 감사합니다!
