### ISSUE TITLE
[SwiftLint] file name rule 수정 건의

### ISSUE THREAD

**Issue by yeonduing** [Nexters/Fancy-Mouse-iOS#5]
현재 `WordUseCases` 라는 파일 안에 Word와 관련된 UseCase 들을 한 번에 모아두려고 하고 있습니다.
각 유스케이스가 프로토콜이라 몇 줄 되지 않아서 개별 파일로 분리하는 것이 더 보기 불편하지 않을까 싶은데

1. 여러 객체나 프로토콜을 모아둔 파일에서 대표할 수 있는 이름으로 사용한다. (예. WordUseCases -> WordUseCase)
2. file name 룰 안에 excluded로 예외처리 하고 싶은 파일을 넣는다.
3. file name 룰을 제거한다.

셋 중 어떤게 좋을지 의견 댓글로 남겨주세요.

**Comment by lsh424** [comment]
1안으로 가용
